import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/shared/style/preset/globals.scss";
import deco from "@/shared/style/deco.module.scss";
import layout from "./layout.module.scss";
import clsx from "clsx";
import { Header } from "@/widget/header/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          deco.spot,
          layout.layout,
        )}
      >
        <Header></Header>
        <main>{children}</main>
      </body>
    </html>
  );
}
