import { gilroy } from "@/shared/font";
import { sDeco } from "@/shared/style";
import clsx from "clsx";

import "@/shared/style/test.scss";

import type { Metadata } from "next";

import page from "@/shared/style/fundamental/page.module.scss";
import { Header } from "@/widget/header";
import { Footer } from "@/widget/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(page.size, page.geometri, page.scrollbar)}>
      <body className={clsx(gilroy.className, sDeco.spot, page.base)}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
