import { gilroy } from "@/shared/font";
import deco from "@/shared/style/deco.module.scss";
import "@/shared/style/preset/globals.scss";
import { Header } from "@/widget/header/ui/header";
import clsx from "clsx";
import type { Metadata } from "next";
import layout from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(gilroy.className, deco.spot, layout.layout)}>
        <Header></Header>
        <main>{children}</main>
      </body>
    </html>
  );
}
