const POSITION_LIST = [
  {
    id: 1,
    position: "Affiliate Manager",
    postingDate: "2023-02-15",
    about:
      "We are looking for: a candidate with strong English and communicative skills to work with webmasters in order to extend and maintain new traffic sources.",
    responsibilities: [
      "Search for new traffic sources and new potential affiliates;",
      "Maintain communication with partners to meet all business needs and build long-term relationships;",
      "Monitor, analyze and optimize campaign performance;",
      "Improve connections with new partners to increase profits;",
      "Monitor the effectiveness of newly engaged partners;",
      "Attend specialized conferences Sigma Malta and iGB London, Amsterdam, Berlin to meet up with existing affiliates and to establish new partnerships.",
    ],
    requirements: [
      "Experience on the position of affiliate manager for 1+ year, preferably iGaming vertical;",
      "Experience in working with different marketing models: Revenue Share, CPA, Hybrid;",
      "Experience in searching for new partners and the ability to build strong long-term relationships;",
      "Upper-Intermediate written and oral English;",
      "Experience in working with SoftSwiss brand and tracking platform is a plus;",
    ],
    employmentType: "Full Time",
    location: "Office/Remote",
    level: "Middle, Senior",
  },
  {
    id: 2,
    position: "Content Manager",
    postingDate: "2023-03-12",
    about:
      "We are looking for a highly organized Content Manager to create, edit, and maintain high-quality content across our digital platforms.",
    responsibilities: [
      "Develop and manage the content strategy aligned with marketing goals;",
      "Coordinate with designers, writers, and marketing teams to produce engaging content;",
      "Ensure all content is optimized for SEO and adheres to brand guidelines;",
      "Monitor content performance using analytics tools and adjust strategies accordingly;",
      "Manage the content calendar and meet deadlines for publishing.",
    ],
    requirements: [
      "Proven experience as a Content Manager or similar role;",
      "Strong understanding of SEO and content optimization;",
      "Excellent writing and editing skills in English;",
      "Experience with content management systems (e.g., WordPress);",
      "Ability to manage multiple projects simultaneously.",
    ],
    employmentType: "Full Time",
    location: "Remote",
    level: "Middle",
  },
  {
    id: 3,
    position: "BI Engineer",
    postingDate: "2023-03-18",
    about:
      "We are seeking a BI Engineer to design and implement business intelligence solutions that help drive data-driven decision-making.",
    responsibilities: [
      "Develop and maintain data models, dashboards, and reports;",
      "Collaborate with business stakeholders to understand reporting requirements;",
      "Ensure data accuracy and integrity across systems;",
      "Optimize and improve existing BI tools and processes;",
      "Stay updated on industry trends and new BI technologies.",
    ],
    requirements: [
      "Experience in BI tools such as Tableau, Power BI, or Looker;",
      "Strong SQL and data modeling skills;",
      "Experience with ETL processes and tools;",
      "Familiarity with cloud platforms like AWS or Azure is a plus;",
      "Good problem-solving and analytical skills.",
    ],
    employmentType: "Full Time",
    location: "Office",
    level: "Junior, Middle",
  },
  {
    id: 4,
    position: "Vip Manager",
    postingDate: "2023-04-01",
    about:
      "We are looking for a VIP Manager to enhance relationships with our high-value clients and provide exceptional service.",
    responsibilities: [
      "Manage a portfolio of VIP clients, ensuring high satisfaction and loyalty;",
      "Develop and implement personalized engagement strategies;",
      "Analyze client data to identify opportunities for improved service;",
      "Coordinate VIP events and promotions to strengthen client relationships;",
      "Handle escalated issues and ensure swift resolution.",
    ],
    requirements: [
      "Proven experience in a customer-facing role, preferably in the iGaming industry;",
      "Strong interpersonal and communication skills;",
      "Ability to analyze client behavior and tailor services accordingly;",
      "Fluency in English and an additional language is a plus;",
      "Flexibility to travel for client events and meetings.",
    ],
    employmentType: "Full Time",
    location: "Remote",
    level: "Middle",
  },
  {
    id: 5,
    position: "Promo Manager",
    postingDate: "2023-04-10",
    about:
      "We are searching for a Promo Manager to plan, execute, and analyze promotional campaigns to drive user engagement and revenue growth.",
    responsibilities: [
      "Design and manage promotional campaigns across multiple channels;",
      "Collaborate with marketing and design teams to create promotional materials;",
      "Analyze campaign performance and optimize strategies;",
      "Monitor market trends and competitor activities;",
      "Ensure compliance with regulatory guidelines for promotions.",
    ],
    requirements: [
      "Experience in managing promotional campaigns, preferably in the gaming or e-commerce industry;",
      "Strong analytical skills and attention to detail;",
      "Excellent organizational and project management abilities;",
      "Knowledge of digital marketing tools and techniques;",
      "Fluency in English is required.",
    ],
    employmentType: "Full Time",
    location: "Remote",
    level: "Junior, Middle",
  },
  {
    id: 6,
    position: "Graphic Designer",
    postingDate: "2023-04-20",
    about:
      "We are hiring a creative Graphic Designer to produce high-quality visual content that aligns with our brand and marketing goals.",
    responsibilities: [
      "Design visually appealing graphics for digital and print media;",
      "Collaborate with the marketing team to create promotional materials;",
      "Maintain brand consistency across all design projects;",
      "Work on multiple projects and meet tight deadlines;",
      "Stay updated on design trends and software tools.",
    ],
    requirements: [
      "Proven experience as a Graphic Designer with a strong portfolio;",
      "Proficiency in design tools such as Adobe Creative Suite (Photoshop, Illustrator, InDesign);",
      "Strong understanding of design principles and typography;",
      "Attention to detail and creative problem-solving skills;",
      "Experience with video editing or motion graphics is a plus.",
    ],
    employmentType: "Full Time",
    location: "Remote",
    level: "Junior, Middle",
  },
  // { position: "Content Manager" },
  // { position: "BI Engineer" },
  // { position: "Vip Manager" },
  // { position: "Promo Manager" },
  // { position: "Graphic Designer" },
];
